grafana:
    adminUser: ENC[AES256_GCM,data:zPZwS6Y=,iv:9H2eua9Giqt9t+uX0FF3ZB0ggfTmA3S0jziCaQZOapA=,tag:0aZicrTUU4PbOoHgzToi0w==,type:str]
    adminPassword: ENC[AES256_GCM,data:r/D6GH/8ugU=,iv:F6n5Nwoh89+JdbyrjlZfq0CoKQW/HB2OG9OJNK4/AwY=,tag:val/zw28nqAOP/550JHneg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:412514615512:alias/demo-sops
          created_at: "2025-11-06T07:18:16Z"
          enc: AQICAHjER4aSOZfVn5nbDpPy/qneq5DXVbnhmLHXmobAcGnRTwGn1NcOoZJk+brUu82PKwFiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMuk18HVpL4CezwognAgEQgDsj5yxv7j6EDUkZP+BWJrMirL7q8aMAdW4lqE8f3GPz/353+64Bx73Nd6sFBEf/nupKqI9GcqKTkWlfPA==
          aws_profile: ""
    lastmodified: "2025-11-06T07:18:17Z"
    mac: ENC[AES256_GCM,data:8H/9/wticKHTWE7O+KZDKmLuNjODzlqC5QgET910bAxQ+zMIAX/Sgfc/MGFJ2L9k+QnO3cJ7R4inBuIkITsxYK/lL++29e7uEREsNS598ZaL4LbIKoL3GcRv5lZgxgXUiOJbUdWtQKi+sPzGt/DpnkXKxjDjpIMtxLR9b8Z5TVM=,iv:pCM0ak78MRptgOSTZnY8JUMKqmOYSIc2h7D5iifCtjw=,tag:qSZoIz+bWICx5eBizQr42g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
