grafana:
  enabled: true  
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  
  # Admin credentials (from secrets.yaml)
  # admin:admin / changeme:changeme
  
  # Persistence (disabled for Kind)
  persistence:
    enabled: false
  # EKS: Enable with EFS
  # persistence:
  #   enabled: true
  #   type: pvc
  #   storageClassName: efs-sc
  #   existingClaim: pvc-grafana
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 30Gi
  #   finalizers:
  #     - kubernetes.io/pvc-protection

  # serviceAccount:
  # create: true
  # name: grafana-sa
  # autoMount: true
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::412514615512:role/eks-sa-grafana-dev

  
  # Grafana configuration
  grafana.ini:
    server:
      root_url: http://grafana.localhost  # KIND
      # root_url: https://grafana.ymishkhas.cloud  # EKS
  
  # Auto-import dashboards from ConfigMaps
  sidecar:
    dashboards:
      enabled: true
      enableNewTablePanelSyntax: true
    datasources:
      enabled: true
      uid: prometheus
      alertmanager:
        enabled: true
        uid: alertmanager
        handleGrafanaManagedAlerts: true
        implementation: prometheus
  
  # Enable ServiceMonitor for Prometheus scraping
  serviceMonitor:
    enabled: true
    labels:
      release: observability
  
  # Service type
  service:
    type: ClusterIP  # Istio will expose this