configs:
    secret:
        createSecret: ENC[AES256_GCM,data:LFybjw==,iv:UkohKTbHNXOua/tNt/puiTEAfPVKPXST5CT2CZMLTTI=,tag:JbpZBNCVEcXGZUU/rXIrcQ==,type:bool]
        argocdServerAdminPassword: ENC[AES256_GCM,data:yLHGO+JqsIs=,iv:0Dz552op3XbWqnqjSh07CeYpERZnzAPaBeylJOT9ldo=,tag:zp6hLPVKYfdqQlu7k6ADPg==,type:str]
        argocdServerAdminPasswordMtime: ENC[AES256_GCM,data:xR7li0xeGdw8U6Gyz9ZWVrO7vpM=,iv:E8NSIB8MDInypM97iuC5Rxj0FM2CdrKKg6H+teUwgtw=,tag:xpoNmPio3R1vzquvWMz8Xg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:412514615512:alias/demo-sops
          created_at: "2025-11-05T08:47:37Z"
          enc: AQICAHjER4aSOZfVn5nbDpPy/qneq5DXVbnhmLHXmobAcGnRTwGmW/9vU7seSeksDy9OfkxJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKY7V4hw4iiZxUwNmAgEQgDvZjOJgMn5lrWMz3GPYU5Mt7rXb7lzs5IJ/nKvMGPtrpQVSg5GK5C0w8Zjh9UkC4afcqDuJqQ+AMu+aPw==
          aws_profile: ""
    lastmodified: "2025-11-05T08:47:37Z"
    mac: ENC[AES256_GCM,data:4cm23Usr5SoKiTP+cEIszd3/3sTaF5rVXvJXm+F9CRIdJ+ATZiuaeUFCZHHdgcqK92+PtIgaTBNb+/kmMKJcN3i/09UKxuPL7I9czhf75eP9qoGb1TUcNtN7KcP5Tkfdniub/bwuEnGhh2FK59me5MNWHribgklJPld9cMp7Hcg=,iv:HIFk8F5rGzpztV13Ha/YmobWaDIWcwsGCBLbwIz+I7U=,tag:iPtupq/q1xEjJ1a5QuOKkg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
