resources:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: global-alb-ingress
      namespace: istio-system
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:412514615512:certificate/0c94cd03-449e-4758-83a3-8d1520a71d20
        alb.ingress.kubernetes.io/success-codes: '200,404,301'
    spec:
      ingressClassName: alb
      rules:
      - host: "*.ymishkhas.cloud"
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-gateway
                port:
                  number: 80
  - apiVersion: networking.istio.io/v1
    kind: Gateway
    metadata:
      name: global-ymishkhas-gateway
      namespace: istio-system
    spec:
      selector:
        istio: gateway 
      servers:
      - port:
          number: 80
          name: http
          protocol: HTTP  # Receives traffic from ALB (already decrypted)
        hosts:
        - "*"

  # VirtualService: ArgoCD
  - apiVersion: networking.istio.io/v1
    kind: VirtualService
    metadata:
      name: argocd
      namespace: argocd
    spec:
      gateways:
        - istio-system/global-ymishkhas-gateway
      hosts:
        - argocd.ymishkhas.cloud
      http:
        - match:
            - uri:
                prefix: /
          route:
            - destination:
                host: argocd-server.argocd.svc.cluster.local
                port:
                  number: 80

  # VirtualService: Grafana
  - apiVersion: networking.istio.io/v1
    kind: VirtualService
    metadata:
      name: grafana
      namespace: monitoring
    spec:
      gateways:
        - istio-system/global-ymishkhas-gateway
      hosts:
        - grafana.ymishkhas.cloud
      http:
        - match:
            - uri:
                prefix: /
          route:
            - destination:
                host: observability-grafana.monitoring.svc.cluster.local
                port:
                  number: 80

  # VirtualService: Prometheus
  - apiVersion: networking.istio.io/v1
    kind: VirtualService
    metadata:
      name: prometheus
      namespace: monitoring
    spec:
      gateways:
        - istio-system/global-ymishkhas-gateway
      hosts:
        - prometheus.ymishkhas.cloud
      http:
        - match:
            - uri:
                prefix: /
          route:
            - destination:
                host: prometheus-operated.monitoring.svc.cluster.local
                port:
                  number: 9090

  # ServiceMonitors for Istio Metrics
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: istio-gateway
      namespace: istio-system
      labels:
        release: observability 
    spec:
      selector:
        matchLabels:
          istio: gateway
      endpoints:
      - interval: 30s
        path: /stats/prometheus
        port: http-envoy-prom

  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: istio-istiod
      namespace: istio-system
      labels:
        release: observability
    spec:
      selector:
        matchLabels:
          app: istiod
      endpoints:
      - interval: 30s
        path: /metrics
        port: http-monitoring
  
  # To see istio gateway logs,
  - apiVersion: telemetry.istio.io/v1
    kind: Telemetry
    metadata:
      name: gateway-access-logs-metrics
      namespace: istio-system
    spec:
      selector:
        matchLabels:
          istio: gateway
      accessLogging:
        - providers:
          - name: envoy
      metrics:
        - providers:
          - name: prometheus