alertmanager:
    config:
        receivers:
            - name: ENC[AES256_GCM,data:9Vg2GzbE9c8X5vk=,iv:KvgMhrci4sFdfe8LOt9RZYtZuycn33hTOXbIZ/Kt2hY=,tag:ok2/vfDNJbuvHZv59l0tzA==,type:str]
              discord_configs:
                - webhook_url: ENC[AES256_GCM,data:chZEo3fr90/4xCCdXg2PrdRixFfsyeAH6ajgoPLrLI3I728o8/z/3oOgRV4dWLI2ByMobPIuuggi4KeZG/Tj1jNcZLqrJpyaiuijZvA2rSmhTJUXqseyJNmN54G15n+v/NqSsVqmyUMVaDkRfs4fIMzyLEnOaPiyEA==,iv:8tzzvoVaUGnpcbrIBzcZ1w/DJMkqg2QDfegcf8kcI0s=,tag:pgD+ou0BaSO4I7YxIigNjg==,type:str]
                  username: ENC[AES256_GCM,data:jfbqMNCWs7RLGph41SmD9OdLW5yY,iv:iNItlsPjl/w4HHPl06mrvl/TM1cHL6Ahxm+D39zjqMk=,tag:QZxyvJf2JUMCzc+abGttrA==,type:str]
                  title: ENC[AES256_GCM,data:l424HJ4BZEhmbYWAdSzcFMMvoHy8qD0Kt7Yf58F+Js21nihwMpMY/A==,iv:zxpwX9PfPX9jPAtdkAEIBzmALz1jbNEF7xrcai+JLrw=,tag:KlZ7vfpOsFsH88TBSWJKMA==,type:str]
                  message: ENC[AES256_GCM,data:+ws1UL+pTGlJNwKAIcTAdfsidyRKl5SvDHWx8lxHoCr/xwe1Rir9+2FF,iv:W87TuRx+5YYIpLA+iEV3L/BHMGwzmWkmznye4hySjOg=,tag:d3aZt0zt9yIXwMki5lxuGQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:412514615512:alias/demo-sops
          created_at: "2025-11-06T07:29:21Z"
          enc: AQICAHjER4aSOZfVn5nbDpPy/qneq5DXVbnhmLHXmobAcGnRTwGTZ7yqMsNeAOBB9POCyCc8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwZ2FsB08RlYk2SFnAgEQgDs+6KNuCAkAhJ1IxVTlAdKFnxPNzKOyWndS2biogSZVrGywfhtwpyG6SfSzELfRQtOogtejm9avICzP/w==
          aws_profile: ""
    lastmodified: "2025-11-06T07:29:22Z"
    mac: ENC[AES256_GCM,data:/2v1HkdQpbilYIOS3elSo2Tukhm85fdveZhcCsrXYXhJVzaIk2kM/hAUhI9G+nkW5vu7kQQsD/WTnCsCWYv9CUro4pvI3rDOMIyNEzdpJhGijgm1GAL9Auho3Rkq4+kesylNVnNuR6sDwFhW+HgfFG6Za40ScRBXM4qtGS8QxUA=,iv:0Vg9mhkqR6qnsqPa13y3gzvSZcUwMapblmstJi5Iz5k=,tag:x8YrB+C0SfgjUBwQbyfyUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
