alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1    
    retention: 120h
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
  
  # Alert routing configuration
  config:
    global:
      resolve_timeout: 5m
    
    # Alert routing rules
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'devops-team'
      
      # Route specific alerts
      routes:
        - receiver: 'devops-team'
          matchers:
            - 'team =~ devops|cloud'
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
      - target_matchers:
          - 'alertname = InfoInhibitor'
    templateFiles:
    # ref: https://prometheus.io/docs/alerting/latest/notifications/
      global.tmpl: |
        {{ define "URL" }}{{ .ExternalURL | reReplaceAll ".*alertmanager\\.(.*)" "$1" }}{{ end }}
      discord.tmpl: |
        {{ define "discord.techrar.title" -}}
          {{- $first := index .Alerts 0 -}}
          [{{ $first.Status | toUpper }}]
        {{- end }}
        {{ define "discord.techrar.message" -}}
          {{- $root := . -}}
          {{- range .Alerts }}
            **Alert:** {{ .Labels.alertname }}  
            **Severity:** {{ .Labels.severity | toUpper }}  
            {{- if .Annotations.description }}
            **Description:** {{ .Annotations.description }}
            {{- else if .Annotations.message }}
            **Description:** {{ .Annotations.message }}
            {{- end }}
            **StartedAt:** {{ .StartsAt }}
            **Link:** {{ template "URL" $root }}  

            **Details:**
            {{- range .Labels.SortedPairs }}
            • **{{ .Name }}:** {{ .Value }}
            {{- end }}
            {{ println "" }}
          {{- end }}
        {{- end }}

  # ServiceMonitor for Prometheus
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: observability