apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl-pod
  name: curl-pod
  namespace: default
spec:
  containers:
  - args:
    - -c
    - sleep infinity
    command:
    - /bin/sh
    image: curlimages/curl
    imagePullPolicy: Always
    name: curl-pod
    stdin: true
    tty: true
    resources: {}
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: CriticalAddonsOnly
    operator: Equal
    value: "true"